# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x10serialisationLab\"\xa3\x01\n\x07Message\x12\x0e\n\x06string\x18\x01 \x02(\t\x12\x0c\n\x04list\x18\x02 \x03(\x05\x12\x31\n\x04\x64ict\x18\x03 \x03(\x0b\x32#.serialisationLab.Message.DictEntry\x12\x0b\n\x03int\x18\x04 \x02(\x05\x12\r\n\x05\x66loat\x18\x05 \x02(\x02\x1a+\n\tDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE_DICTENTRY._options = None
  _MESSAGE_DICTENTRY._serialized_options = b'8\001'
  _MESSAGE._serialized_start=36
  _MESSAGE._serialized_end=199
  _MESSAGE_DICTENTRY._serialized_start=156
  _MESSAGE_DICTENTRY._serialized_end=199
# @@protoc_insertion_point(module_scope)
